### ISSUE TITLE
Empty response from calling make_type3_msg()

### ISSUE THREAD

**Issue by samirame** [dyduyu/ntlm#1]
Hi! 

I have some issue calling the make_type3_msg(). Here are the steps which I take:

1- I call the make_type1_msg() to create the _negotiate_ string.

2- I then send the _negotiate_ string to the server and obtain the _challenge_ string from the header. It looks something like:
TlRMTVNTUAACAAAADgAOADgAAAAFgoECljZZTJMBjxcAAAAAAAAAAI4AjgBGAAAABgOAJQAAAA9EAEEAUwBQAEwAVQBTAAIADgBEAEEAUwBQAEwAVQBTAAEADABBAFMAUwBFAEMATwAEABYAZABhAHMAUABsAHUAcwAuAG8AcgBnAAMAJABBAHMAcwBlAGMAbwAuAGQAYQBzAFAAbAB1AHMALgBvAHIAZwAFABYAZABhAHMAUABsAHUAcwAuAG8AcgBnAAcACAAKc9UuVwLUAQAAAAA=

3- I pass the _challenge_ string I extracted from the server response to the make_type3_msg() function with the hope to create the _authorization_ string. However, the Message2Handle::isValid check returns false at line 552 ntlm.cpp:

`			if ((56 + msg2.target_name_len + msg2.target_info_len) != msg2_buff_len)
			{
				return false;
			}
`

Could you please let me know what could be the problem?

Thanks in advance!

**Comment by dyduyu** [comment]
Hello @samirame 
Thanks so much for feedback! It's my [bug](https://github.com/dyduyu/ntlm/commit/99afccb3909b5e2eeed5c37aca55d958ba7226f2). I think you must have fixed the issue ^_^
\----
btw, I'm sorry for late response, I didn't see the notification in my mail.
